include: ../analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    avoid_as: false # Disabled so we can gradually migrate to no implicit dynamic.
